#!/bin/zsh -eu

DEFAULT_BRANCH=`git remote show origin | grep 'HEAD branch' | awk '{print $NF}'`;

NEW_BRANCH=$1;

if [[ -z $1  ]]; then
  echo ' Use this branch as feature branch.';
  BASE_BRANCH=`git base`;
  NEW_BRANCH=`git rev-parse --abbrev-ref @`;
else
  BASE_BRANCH=`git rev-parse --abbrev-ref @`;
fi;

if [[ $BASE_BRANCH = $DEFAULT_BRANCH ]]; then
  echo '  🔥ATTENTION!! you are trying to make branch from ['$DEFAULT_BRANCH']🔥';
fi;

read "yn?  You want to make Base Branch:$BASE_BRANCH -> New Branch:$NEW_BRANCH? (y/n)  ";

case $yn in
  [yY]* ) echo "  🆗 Let's Start!!";;
  * ) exit 1;;
esac;

if [[ ! $(git branch | grep $NEW_BRANCH) ]]; then
  git checkout -b $NEW_BRANCH;
  git commit --allow-empty -m $NEW_BRANCH;
  # echo "make new branch:"$NEW_BRANCH
fi;

git branch -r | grep $NEW_BRANCH || git push -u origin $NEW_BRANCH;
# git branch -r | grep $NEW_BRANCH || echo "push branch";
echo '✅ Success! Create remote branch';

git remote show origin | grep -q 'github' \
  && gh pr create -d -B ${BASE_BRANCH} -H ${NEW_BRANCH} \
  || hub pull-request --draft -b $BASE_BRANCH;
# git remote show origin | grep -q 'github' \
#   && echo "github" \
#   || echo "ghe"


echo '✅ Success! create draft branch';
