#!/bin/zsh -e

if [[ -n $1 ]]; then
  # 引数あり：新しいブランチを作成
  NEW_BRANCH=$1
  echo "⚒️ Creating new branch: [$NEW_BRANCH]"

  if ! git branch | grep -q "^[* ] ${NEW_BRANCH}$"; then
    git checkout -b "$NEW_BRANCH"
    git commit --allow-empty -m "$NEW_BRANCH"
  fi
else
  # 引数なし：現在のブランチを使う
  NEW_BRANCH=$(git rev-parse --abbrev-ref @)
  echo "👀 Using current branch: [$NEW_BRANCH]"
fi

# リモートにプッシュ
git branch -r | grep -q "origin/${NEW_BRANCH}$" || git push -u origin "$NEW_BRANCH"
echo '✅ Success! Created remote branch'

# PRを作成
if ! gh pr create -d; then
  echo '❌ Failed to create draft PR'
  exit 1
fi

echo '✅ Success! Created draft PR'
